
package org.apache.servicemix.samples.wsdl_first;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Progress FUSE Services Framework 2.2.11-fuse-00-00
 * Sat Jul 25 18:40:36 CEST 2015
 * Generated source version: 2.2.11-fuse-00-00
 * 
 */

@WebFault(name = "UnknownPersonFault", targetNamespace = "http://servicemix.apache.org/samples/wsdl-first/types")
public class UnknownPersonFault extends Exception {
    public static final long serialVersionUID = 20150725184036L;
    
    private org.apache.servicemix.samples.wsdl_first.types.UnknownPersonFault unknownPersonFault;

    public UnknownPersonFault() {
        super();
    }
    
    public UnknownPersonFault(String message) {
        super(message);
    }
    
    public UnknownPersonFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownPersonFault(String message, org.apache.servicemix.samples.wsdl_first.types.UnknownPersonFault unknownPersonFault) {
        super(message);
        this.unknownPersonFault = unknownPersonFault;
    }

    public UnknownPersonFault(String message, org.apache.servicemix.samples.wsdl_first.types.UnknownPersonFault unknownPersonFault, Throwable cause) {
        super(message, cause);
        this.unknownPersonFault = unknownPersonFault;
    }

    public org.apache.servicemix.samples.wsdl_first.types.UnknownPersonFault getFaultInfo() {
        return this.unknownPersonFault;
    }
}
